### PR TITLE
Refactor codebase

### PR DESCRIPTION
**Pull request by Sahilgat**
- Refactor codebase to remove several person instances, addressbook instances and begin work on refactoring storage.

- Open PR with failing build so rest can see refactor changes before final merge

### CODE REVIEW

**Comment by Sahilgat** [comment]
The refactor makes a lot of the old tests redundant, but we still need to refer to them to add our own tests. I'll try to leave the test for reference where possible or adapt it for Flashcard use which everyone can then adapt for Cheatsheet and Notes respectively

**Comment by Sam-limyr** [comment]
Okay; keep us updated!

**Comment by Sahilgat** [comment]
Latest pushes fixes #272 and #265 . Currently working on refactoring relevant storage tests and deleting some unused tests.

**Comment by Sahilgat** [comment]
A tests in StartTimeTrialCommandTest, ViewFlashcardCommandTest and FilterFlashcardByTagCommand were broken respectively. I suspect this is because added missing checks to ModelManager equality which previously only checked for equality between filteredNoteList. Referred to @chanjunren and temporarily commented out the 3 tests.

**Comment by jaesimin** [comment]
Thanks for helping us refactoring the codes!

**Pull request merged**
